DROP TABLE IF EXISTS samples;
DROP TABLE IF EXISTS cruises;
DROP TABLE IF EXISTS intervals;
DROP TABLE IF EXISTS repositories;

CREATE TABLE repositories (
  id integer,
  facility text,
  facility_code text,
  other_link text,
  sample_count integer,
  facility_comment text,
  inst_code text,
  addr1 text,
  addr2 text,
  addr3 text,
  addr4 text,
  contact1 text,
  contact2 text,
  contact3 text,
  email_link text,
  url_link text,
  ftp_link text
);

CREATE TABLE intervals (
  id	integer,
  facility	json,
  platform	string,
  cruise	string,
  sample	string,
  device	string,
  interval	integer,
  depth_top	integer,
  depth_bot	integer,
  lith1	string,
  lith2	string,
  text1	string,
  text2	string,
  comp1	string,
  comp2	string,
  comp3	string,
  comp4	string,
  comp5	string,
  comp6	string,
  description	string,
  ages	json,
  absolute_age_top	string,
  absolute_age_bot	string,
  weight	real,
  rock_lith	string,
  rock_min	string,
  weath_meta	string,
  remark	string,
  munsell_code	string,
  exhaust_code	string,
  photo_link	string,
  lake	string,
  int_comments	string,
  igsn	string,
  imlgs	string
);


CREATE TABLE cruises (
  id integer,
  cruise text,
  year integer,
  legs json,
  facilities json,
  platforms json,
  links json
);

CREATE TABLE samples (
  id integer,
  facility json,
  facility_code text,
  cruise text,
  igsn text,
  sample text,
  platform text,
  device text,
  year integer,
  leg text,
  storage_meth text,
  begin_date text,
  lat real,
  lon real,
  water_depth real,
  cored_length text,
  latlon_orig text,
  lake text,
  publish text,
  province text,
  end_date text,
  end_lat real,
  end_lon real,
  end_water_depth real,
  cored_length_mm integer,
  cored_diam integer,
  cored_diam_mm integer,
  pi text,
  other_link text,
  last_update integer,
  sample_comments text,
  show_sampl text,
  ship_code text,
  imlgs text,
  cruise_id integer,
  objectid text,
  cruise_url text,
  leg_url text,
  repository_url,
  texture text,
  mineralogy text,
  remark text,
  weathering text,
  age text,
  interval_igsn text,
  lithologic_composition text,
  rock_lithology text
);

